music_directory         "/storage/music"
playlist_directory      "/storage/.config/mpd/playlists"
db_file                 "/storage/.cache/mpd/database"
state_file              "/storage/.cache/mpd/state"
sticker_file            "/storage/.cache/mpd/sticker.sql"

bind_to_address         "/run/mpd/socket"
bind_to_address         "127.0.0.1"
port                    "6600"

auto_update             "yes"
restore_paused          "yes"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"
filesystem_charset      "UTF-8"
replaygain              "auto"
zeroconf_enabled        "no"

audio_output {
    type                "pulse"
    name                "aleph"
}
